### ISSUE TITLE
How to open the console/ cli via this addon to supervisor in hass.io

### ISSUE THREAD

**Issue by Baggerfahrer** [devRoemer/hassio-homegear-generic#3]
# Problem/Motivation

Hey!
I would like to access the cli of homegear to pair a thermostat with a window sensor.
Normally, the cli can be accessed easily via the terminal, see here the instructions:
[https://doc.homegear.eu/homegear-homematicbidcos/adding_devices.html#pair-a-device-using-the-cli](url)
As there is no terminal easily accessible via hass.io, i do not have an idea how to do it at the moment.

Any tipps?

## Expected behavior

no need to enter this data here

## Actual behavior

How to enter the cli via hass.io....? many thanks!

## Steps to reproduce

no need to enter this data here

## Proposed changes

no need to enter this data here

**Comment by Baggerfahrer** [comment]
found it out by myself:

HowToDO: [https://community.home-assistant.io/t/protip-how-to-get-shell-in-actual-homeassistant-or-addon-container-when-using-hassio/48760](url)

**Comment by devRoemer** [comment]
Thanks for your feedback.

I added a documentation with detailed steps to access the homegear cli:
https://github.com/devRoemer/hassio-homegear-generic/wiki/Access-via-cli---command-line

**Comment by Baggerfahrer** [comment]
a majpr point is missing in your manual, see the link i added:

`ssh root@hassio -p 22222
At the hassio > prompt run “**login**”`

did you let this out by purpose or was it a mistake?

**Comment by devRoemer** [comment]
I just chose a different approach for users that feel more comfortable by using the web ui to execute commands. After installing the addon https://github.com/hassio-addons/addon-ssh you get an extra menu entry called "Terminal" (see screenshot in the link).

There you are directly logged in without using ssh on linux or putty on windows. It might make sense that i go a little bit more into detail related to the web terminal.

**Comment by devRoemer** [comment]
Added another sentence to make it more clear how to access the terminal

**Comment by Baggerfahrer** [comment]
no clue why this way is not applicable for me....
![image](https://user-images.githubusercontent.com/25987294/118348233-2e5cb600-b549-11eb-828d-1e818a12af8d.png)

i need to go the way for the ssh access via port 22222, the port 22 via the web terminal is not working for me.

**Comment by devRoemer** [comment]
I did a quick test with web terminal 8.2.1 and the same os and home assistant core version you are using.
Without protected mode it is working as it should and if i call "docker ps -a" with protected mode i get a proper warning but not "command not found".

That's strange... Especially because with share_sessions set to true (the default) the session should even be shared between ssh and the web client.

The only thing i can imagine is that you have a different user in your web terminal config. Can you please check that it is set to root.
My config looks like this:
![image](https://user-images.githubusercontent.com/41320207/118351500-a8e30100-b55c-11eb-9f0f-dc446c7220c2.png)

**Comment by Baggerfahrer** [comment]
originally, i was not using the ssh client you prefered, but "Terminal & SSH" from the supervisor store. for this test, i changed it to the one you proposed.

i can now confirm that the manual you set up is working!

Somehow, the different versions of the webterminals are not equal in terms of rights, with the other one, i was not able to set the user!

Many thanks!
