### ISSUE TITLE
Integrate Homematic into Home Assistant

### ISSUE THREAD

**Issue by Nec24** [devRoemer/hassio-homegear-generic#9]
# Problem/Motivation
Integrate Homematic into Home Assistant

> (Why the issue was filed)

## Expected behavior
devices shoul appear in emtityes list
> (What you expected to happen)

## Actual behavior
Devices do not appear in entity list

> (What actually happened)

## Steps to reproduce
fresh installation
> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
 I've tryed the following [config](https://github.com/devRoemer/hassio-homegear-generic/wiki/Integrate-Homematic-into-Home-Assistant) for configuration.yaml of home assistant:
`homematic:
  local_ip: 0.0.0.0
  local_port: 36845
  interfaces:
    wireless:
      host: xxxxxxxx-homegear
      port: 2001
      callback_ip: homeassistant
      callback_port: 36845
      resolvenames: json
`

but semas to not comunicate.
Of course the host is edited acourdly

**Comment by devRoemer** [comment]
The best place for support is the homegear forum (https://forum.homegear.eu/).
As a starting point you could have a look at the log files of home assistant and homegear if there is an error somewhere (also consider increasing the log level to debug if not).
With the log entries you might find the issue or get the help required in the homegear forum.
